server:
  port: 8080

spring:
  application:
    name: app-fantacalcio

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/app_fantacalcio}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

jwt:
  secret: YOUR_SECRET_KEY_NEEDS_TO_BE_CHANGED
